version: "3.7"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  deno:
    image: "maxmcd/deno"
    build: .
    ports:
      - "8080:8080"
    networks: 
      - deno
    depends_on:
      - mongo
    command: bash -c "./wait.sh"
    links:
      - mongo
    restart: on-failure
networks:
  deno: {}